package com.lwkslick.ghostmode.client.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;
import dev.isxander.yacl3.api.controller.StringControllerBuilder;

public class GhostModeConfigScreen {

    public static Screen create(Screen parent) {
        GhostModeConfig cfg = GhostModeConfig.get();

        return YetAnotherConfigLib.createBuilder()
                .title(Text.literal("GhostMode"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("General"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Enable GhostMode"))
                                .description(OptionDescription.of(Text.literal("Master on/off switch. Disables all features when off.")))
                                .binding(false, () -> cfg.enabled, val -> { cfg.enabled = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Server IP"))
                                .description(OptionDescription.of(Text.literal("Masks the IP field in Add Server and Direct Connect screens.")))
                                .binding(false, () -> cfg.hideServerIp, val -> { cfg.hideServerIp = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Direct Connect IP"))
                                .description(OptionDescription.of(Text.literal("Masks the IP field in the Direct Connect screen.")))
                                .binding(false, () -> cfg.hideDirectConnect, val -> { cfg.hideDirectConnect = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Username"))
                                .description(OptionDescription.of(Text.literal("Replaces your real username with an alias everywhere on screen.")))
                                .binding(false, () -> cfg.hideUsername, val -> { cfg.hideUsername = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<String>createBuilder()
                                .name(Text.literal("Username Alias"))
                                .description(OptionDescription.of(Text.literal("The name shown in place of your real username.")))
                                .binding("Streamer", () -> cfg.usernameAlias, val -> { cfg.usernameAlias = val; cfg.save(); })
                                .controller(StringControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                .name(Text.literal("F3 Filter"))
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Enable F3 Filter"))
                        .description(OptionDescription.of(Text.literal("Master toggle. When on, hides selected F3 info at the render layer.")))
                        .binding(false, () -> cfg.hideF3, val -> { cfg.hideF3 = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Location"))
                        .description(OptionDescription.of(Text.literal("Hides XYZ, Block, Chunk and Facing lines.")))
                        .binding(false, () -> cfg.hideF3Location, val -> { cfg.hideF3Location = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Biome"))
                        .description(OptionDescription.of(Text.literal("Hides the Biome line.")))
                        .binding(false, () -> cfg.hideF3Biome, val -> { cfg.hideF3Biome = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Looking At"))
                        .description(OptionDescription.of(Text.literal("Hides the looking at block and entity lines.")))
                        .binding(false, () -> cfg.hideF3LookingAt, val -> { cfg.hideF3LookingAt = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Memory"))
                        .description(OptionDescription.of(Text.literal("Hides Allocated and Off-heap memory lines.")))
                        .binding(false, () -> cfg.hideF3Memory, val -> { cfg.hideF3Memory = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide System Specs"))
                        .description(OptionDescription.of(Text.literal("Hides Java, CPU, GPU and Display lines.")))
                        .binding(false, () -> cfg.hideF3SystemSpecs, val -> { cfg.hideF3SystemSpecs = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Watermark"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Enable Watermark"))
                                .description(OptionDescription.of(Text.literal("Shows your channel name on screen while streaming.")))
                                .binding(false, () -> cfg.watermarkEnabled, val -> { cfg.watermarkEnabled = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<String>createBuilder()
                                .name(Text.literal("Watermark Text"))
                                .description(OptionDescription.of(Text.literal("The text shown as your watermark.")))
                                .binding("YourChannel", () -> cfg.watermarkText, val -> { cfg.watermarkText = val; cfg.save(); })
                                .controller(StringControllerBuilder::create)
                                .build())
                        .option(Option.<String>createBuilder()
                                .name(Text.literal("Position"))
                                .description(OptionDescription.of(Text.literal("Where the watermark appears: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT, ACTION_BAR")))
                                .binding("ACTION_BAR", () -> cfg.watermarkPosition, val -> { cfg.watermarkPosition = val; cfg.save(); })
                                .controller(StringControllerBuilder::create)
                                .build())
                        .option(Option.<java.awt.Color>createBuilder()
                                .name(Text.literal("Color"))
                                .description(OptionDescription.of(Text.literal("Watermark text color.")))
                                .binding(new java.awt.Color(255, 255, 255), () -> cfg.watermarkColor, val -> { cfg.watermarkColor = val; cfg.save(); })
                                .controller(opt -> dev.isxander.yacl3.api.controller.ColorControllerBuilder.create(opt).allowAlpha(false))
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Opacity (0-255)"))
                                .description(OptionDescription.of(Text.literal("255 = fully visible, 0 = invisible.")))
                                .binding(255, () -> cfg.watermarkOpacity, val -> { cfg.watermarkOpacity = val; cfg.save(); })
                                .controller(opt -> dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Tab List"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Tab List"))
                                .description(OptionDescription.of(Text.literal("Hides the entire tab list when Tab is held.")))
                                .binding(false, () -> cfg.hideTabList, val -> { cfg.hideTabList = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Player Count Only"))
                                .description(OptionDescription.of(Text.literal("Shows the tab list but hides all player names except yours.")))
                                .binding(false, () -> cfg.tabCountOnly, val -> { cfg.tabCountOnly = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Fake Ping (ms)"))
                                .description(OptionDescription.of(Text.literal("Shows a fake ping icon for your own entry. Set to -1 to disable.")))
                                .binding(-1, () -> cfg.fakePing, val -> { cfg.fakePing = val; cfg.save(); })
                                .controller(opt -> dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder.create(opt).range(-1, 999).step(1))
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Fake Coords"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Enable Fake Coords"))
                                .description(OptionDescription.of(Text.literal("Replaces F3 coordinates with random numbers that change on an interval.")))
                                .binding(false, () -> cfg.fakeCoords, val -> { cfg.fakeCoords = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Integer>createBuilder()
                                .name(Text.literal("Randomise Interval (seconds)"))
                                .description(OptionDescription.of(Text.literal("How often the fake coords change. Min 1, max 60.")))
                                .binding(1, () -> cfg.fakeCoordsInterval, val -> { cfg.fakeCoordsInterval = val; cfg.save(); })
                                .controller(opt -> dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder.create(opt).range(1, 60).step(1))
                                .build())
                        .build())
                .save(cfg::save)
                .build()
                .generateScreen(parent);
    }
}