package com.lwkslick.ghostmode.client.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;
import dev.isxander.yacl3.api.controller.StringControllerBuilder;

public class GhostModeConfigScreen {

    public static Screen create(Screen parent) {
        GhostModeConfig cfg = GhostModeConfig.get();

        return YetAnotherConfigLib.createBuilder()
                .title(Text.literal("GhostMode"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("General"))
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Enable GhostMode"))
                                .description(OptionDescription.of(Text.literal("Master on/off switch. Disables all features when off.")))
                                .binding(false, () -> cfg.enabled, val -> { cfg.enabled = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Server IP"))
                                .description(OptionDescription.of(Text.literal("Masks the IP field in Add Server and Direct Connect screens.")))
                                .binding(false, () -> cfg.hideServerIp, val -> { cfg.hideServerIp = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Direct Connect IP"))
                                .description(OptionDescription.of(Text.literal("Masks the IP field in the Direct Connect screen.")))
                                .binding(false, () -> cfg.hideDirectConnect, val -> { cfg.hideDirectConnect = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Text.literal("Hide Username"))
                                .description(OptionDescription.of(Text.literal("Replaces your real username with an alias everywhere on screen.")))
                                .binding(false, () -> cfg.hideUsername, val -> { cfg.hideUsername = val; cfg.save(); })
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.<String>createBuilder()
                                .name(Text.literal("Username Alias"))
                                .description(OptionDescription.of(Text.literal("The name shown in place of your real username.")))
                                .binding("Streamer", () -> cfg.usernameAlias, val -> { cfg.usernameAlias = val; cfg.save(); })
                                .controller(StringControllerBuilder::create)
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                .name(Text.literal("F3 Filter"))
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Enable F3 Filter"))
                        .description(OptionDescription.of(Text.literal("Master toggle. When on, hides selected F3 info at the render layer.")))
                        .binding(false, () -> cfg.hideF3, val -> { cfg.hideF3 = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Location"))
                        .description(OptionDescription.of(Text.literal("Hides XYZ, Block, Chunk and Facing lines.")))
                        .binding(false, () -> cfg.hideF3Location, val -> { cfg.hideF3Location = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Biome"))
                        .description(OptionDescription.of(Text.literal("Hides the Biome line.")))
                        .binding(false, () -> cfg.hideF3Biome, val -> { cfg.hideF3Biome = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Looking At"))
                        .description(OptionDescription.of(Text.literal("Hides the looking at block and entity lines.")))
                        .binding(false, () -> cfg.hideF3LookingAt, val -> { cfg.hideF3LookingAt = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Memory"))
                        .description(OptionDescription.of(Text.literal("Hides Allocated and Off-heap memory lines.")))
                        .binding(false, () -> cfg.hideF3Memory, val -> { cfg.hideF3Memory = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide System Specs"))
                        .description(OptionDescription.of(Text.literal("Hides Java, CPU, GPU and Display lines.")))
                        .binding(false, () -> cfg.hideF3SystemSpecs, val -> { cfg.hideF3SystemSpecs = val; cfg.save(); })
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                .build())
                .save(cfg::save)
                .build()
                .generateScreen(parent);
    }
}